import numpy as np

base_path="/home/nnrthmr/CLionProjects/ma_thesis/data/mapping/2dof_vertical"


# # data1= np.genfromtxt(base_path+"/sing_side_90/manipulabilities_40.csv", delimiter=',')
# # data2= np.genfromtxt(base_path+"/sing_side_120/manipulabilities_40.csv", delimiter=',')
# # data3= np.genfromtxt(base_path+"/sing_side_150/manipulabilities_40.csv", delimiter=',')
# # data4= np.genfromtxt(base_path+"/sing_side_110/manipulabilities_40.csv", delimiter=',')
# # #data5= np.genfromtxt(base_path+"/sing_side_140/manipulabilities_40.csv", delimiter=',')
# # data6= np.genfromtxt(base_path+"/sing_up_0/manipulabilities_40.csv", delimiter=',')
# # data7= np.genfromtxt(base_path+"/sing_up_45/manipulabilities_40.csv", delimiter=',')
# # data8= np.genfromtxt(base_path+"/sing_up_90/manipulabilities_40.csv", delimiter=',')
# # #data9= np.genfromtxt(base_path+"/sing_up_60/manipulabilities_40.csv", delimiter=',')
# # data10= np.genfromtxt(base_path+"/sing_up_30/manipulabilities_40.csv", delimiter=',')

# data1= np.genfromtxt(base_path+"/sing_side_90/manipulabilities.csv", delimiter=',')
# data2= np.genfromtxt(base_path+"/sing_side_120/manipulabilities.csv", delimiter=',')
# data3= np.genfromtxt(base_path+"/sing_side_150/manipulabilities.csv", delimiter=',')
# data4= np.genfromtxt(base_path+"/sing_side_110/manipulabilities.csv", delimiter=',')
# #data5= np.genfromtxt(base_path+"/sing_side_140/manipulabilities.csv", delimiter=',')
# data6= np.genfromtxt(base_path+"/sing_up_0/manipulabilities.csv", delimiter=',')
# data7= np.genfromtxt(base_path+"/sing_up_45/manipulabilities.csv", delimiter=',')
# data8= np.genfromtxt(base_path+"/sing_up_90/manipulabilities.csv", delimiter=',')
# #data9= np.genfromtxt(base_path+"/sing_up_60/manipulabilities.csv", delimiter=',')
# data10= np.genfromtxt(base_path+"/sing_up_30/manipulabilities.csv", delimiter=',')

# data=np.concatenate((data1, data2, data3, data4, data6, data7, data8, data10))
# print(data1.shape)
# print(data2.shape)
# print(data3.shape)
# print(data4.shape)
# #print(data5.shape)
# print(data6.shape)
# print(data7.shape)
# print(data8.shape)
# #print(data9.shape)
# print(data10.shape)
# print(data.shape)
# np.savetxt(base_path+"/sing_combined/manipulabilities.csv", data, delimiter=',')

data0= np.genfromtxt(base_path+"/link1/manipulabilities_20.csv", delimiter=',')
data1= np.genfromtxt(base_path+"/links_combined/manipulabilities_1.csv", delimiter=',')
data2= np.genfromtxt(base_path+"/links_combined/manipulabilities_2.csv", delimiter=',')
data3= np.genfromtxt(base_path+"/links_combined/manipulabilities_3.csv", delimiter=',')
data4= np.genfromtxt(base_path+"/links_combined/manipulabilities_4.csv", delimiter=',')
data5= np.genfromtxt(base_path+"/links_combined/manipulabilities_5.csv", delimiter=',')
data6= np.genfromtxt(base_path+"/links_combined/manipulabilities_6.csv", delimiter=',')
data7= np.genfromtxt(base_path+"/links_combined/manipulabilities_7.csv", delimiter=',')
data8= np.genfromtxt(base_path+"/links_combined/manipulabilities_8.csv", delimiter=',')
data9= np.genfromtxt(base_path+"/links_combined/manipulabilities_9.csv", delimiter=',')
data10= np.genfromtxt(base_path+"/links_combined/manipulabilities_10.csv", delimiter=',')
data11= np.genfromtxt(base_path+"/links_combined/manipulabilities_11.csv", delimiter=',')
data12= np.genfromtxt(base_path+"/links_combined/manipulabilities_12.csv", delimiter=',')
data13= np.genfromtxt(base_path+"/links_combined/manipulabilities_13.csv", delimiter=',')
data14= np.genfromtxt(base_path+"/links_combined/manipulabilities_14.csv", delimiter=',')
data15= np.genfromtxt(base_path+"/links_combined/manipulabilities_15.csv", delimiter=',')
data16= np.genfromtxt(base_path+"/links_combined/manipulabilities_16.csv", delimiter=',')
data17= np.genfromtxt(base_path+"/links_combined/manipulabilities_17.csv", delimiter=',')
#data18= np.genfromtxt(base_path+"/links_combined/manipulabilities_18.csv", delimiter=',')
data19= np.genfromtxt(base_path+"/links_combined/manipulabilities_19.csv", delimiter=',')
data20= np.genfromtxt(base_path+"/links_combined/manipulabilities_20.csv", delimiter=',')
data21= np.genfromtxt(base_path+"/links_combined/manipulabilities_21.csv", delimiter=',')
data22= np.genfromtxt(base_path+"/links_combined/manipulabilities_22.csv", delimiter=',')

data=np.concatenate((data0, data1, data3, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data19, data20, data21, data22))
print(data.shape)
np.savetxt(base_path+"/links_combined/manipulabilities.csv", data, delimiter=',')


